// web3
export const WEB3_INITIALIZED = "WEB3_INITIALIZED";

// account
export const GET_WALLET_INFO_SUCCESS = "GET_WALLET_INFO_SUCCESS";
export const GET_WALLET_INFO_FAIL = "GET_WALLET_INFO_FAIL";

// settings
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";

// transactions
export const SUBMIT_TRANSACTION_SUCCESS = "SUBMIT_TRANSACTION_SUCCESS";
export const SUBMIT_TRANSACTION_FAIL = "SUBMIT_TRANSACTION_FAIL";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
